# docker/supervisor.conf
[supervisord]
nodaemon=true ; Jalankan di foreground
user=root     ; Supervisor perlu root untuk start proses sebagai www-data
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm8.4 -F -R ; Sesuaikan dengan versi PHP Anda (misal: php-fpm8.4). -F (foreground), -R (allow root to run)
autostart=true
autorestart=true
priority=5
user=www-data ; Jalankan PHP-FPM sebagai www-data
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=QUIT

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;" ; -g "daemon off;" penting.
autostart=true
autorestart=true
priority=10
user=root ; Nginx perlu root untuk bind ke port di bawah 1024 (meskipun di sini 8080) dan manage worker processes
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0